FROM python:3.8

WORKDIR /usr/src/app

RUN pip install --upgrade pip

RUN apt-get update && \
    apt-get install -y default-libmysqlclient-dev build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

CMD sh -c 'flask db upgrade && python run.py'
